services:
  - type: web
    name: library-backend
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn library_management_system.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        sync: false
      - key: DB_NAME
        fromDatabase:
          name: library-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: library-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: library-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: library-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: library-db
          property: port
      - key: CORS_ALLOWED_ORIGINS
        sync: false

databases:
  - name: library-db
    plan: free
    databaseName: library_db
    user: library_user

